name: "Setup for translation"
runs:
    using: "composite"
    steps:
        - name: "Setup"
          shell: bash
          run: |
              python3 -m venv virtual_environment
              source virtual_environment/bin/activate
              pip install wheel
              pip install --requirement '# Development/tools/machine_translation/requirements.txt'
